#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -k oe

# Some defaults for the parameters
BIN454=${BIN454:-"$HOME/454/bin"};

# Check mandatory variables
if [[ "$LIB" == "" ]]; then
   echo "Error: LIB is mandatory" >&2
   exit 1;
fi
if [[ "$PDIR" == "" ]]; then
   echo "Error: PDIR is mandatory" >&2
   exit 1;
fi
if [[ "$KVELVET$KSOAP" == "" ]]; then
   echo "Error: KVELVET and/or KSOAP are mandatory" >&2
   exit 1;
fi

# Prepare input
KVELVET=$(echo $KVELVET | sed -e 's/:/ /g')
KSOAP=$(echo $KSOAP | sed -e 's/:/ /g')
NP=$(cat "$PBS_NODEFILE" | wc -l)
CWD=$(pwd)
DIR="$CWD/$LIB.newbler"
LOG="$DIR.log"
module load perl/5.14.4
export PATH=$PATH:$BIN454

# Create project
echo new > $DIR.proc
nohup newAssembly $DIR > $LOG

# Prepare Velvet
if [[ "$KVELVET" != "" ]] ; then
   echo pre-velvet > $DIR.proc
   rm $LIB.velvet.tmp1 &>/dev/null
   for K in $KVELVET ; do
      perl "$PDIR/FastA.filterN.pl" "$LIB.velvet_$K/contigs.fa" >> $LIB.velvet.tmp1
   done
   perl "$PDIR/newbler_preparator.pl" $LIB.velvet.tmp1 $LIB.velvet.tmp2
   cd $DIR
   nohup addRun ../$LIB.velvet.tmp2 >> $LOG
   cd $CWD
fi ;

# Prepare SOAP
if [[ "$KSOAP" != "" ]] ; then
   echo pre-soap > $DIR.proc
   rm $LIB.soap.tmp1 &>/dev/null
   for K in $KSOAP ; do
      cat "$LIB.soap_$K/O.contig" >> $LIB.soap.tmp1
   done
   perl "$PDIR/newbler_preparator.pl" $LIB.soap.tmp1 $LIB.soap.tmp2
   cd $DIR
   nohup addRun ../$LIB.soap.tmp2 >> $LOG
   cd $CWD
fi ;

# Run
cd $DIR
echo newbler > $DIR.proc
nohup runProject -cpu $NP >> $LOG
cd $CWD
echo done > $DIR.proc

