#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -k oe

# Some defaults for the parameters
FORMAT=${FORMAT:-fasta};
INSLEN=${INSLEN:-300};
USECOUPLED=${USECOUPLED:-yes};
USESINGLE=${USESINGLE:-no};
CLEANUP=${CLEANUP:-yes}

# Check mandatory variables
if [[ "$LIB" == "" ]]; then
   echo "Error: LIB is mandatory" >&2
   exit 1;
fi
if [[ "$PDIR" == "" ]]; then
   echo "Error: PDIR is mandatory" >&2
   exit 1;
fi
if [[ "$DATA" == "" ]]; then
   echo "Error: DATA is mandatory" >&2
   exit 1;
fi

# Prepare input
KMER=$PBS_ARRAYID
CWD=$(pwd)
DIR="$CWD/$LIB.velvet_$KMER"

# Run
module load velvet/1.2.10
echo velveth > $DIR.proc
CMD="velveth_101_omp $DIR $KMER -$FORMAT"
if [[ "$USECOUPLED" == "yes" ]]; then
   CMD="$CMD -shortPaired $DATA/$LIB.CoupledReads.fa"
fi
if [[ "$USESINGLE" == "yes" ]]; then
   CMD="$CMD -short $DATA/$LIB.SingleReads.fa"
fi
if [[ "$VELVETH_EXTRA" != "" ]]; then
   CMD="$CMD $VELVETH_EXTRA"
fi
$CMD &> $DIR.hlog
echo velvetg > $DIR.proc
velvetg_101_omp "$DIR" -exp_cov auto -cov_cutoff auto -ins_length "$INSLEN" $VELVETG_EXTRA &> $DIR.glog
if [[ -d $DIR ]] ; then
   if [[ -s $DIR/contigs.fa ]] ; then
      if [[ "$CLEANUP" != "no" ]] ; then
	 echo cleanup > $DIR.proc
	 rm $DIR/Sequences
	 rm $DIR/Roadmaps
	 rm $DIR/*Graph*
      fi
      echo done > $DIR.proc
   else
      echo "$0: Error: File $DIR/contigs.fa doesn't exist, something went wrong" >&2
      exit 1
   fi
else
   echo "$0: Error: Directory $DIR doesn't exist, something went wrong" >&2
   exit 1
fi
