#!/bin/bash
#PBS -l nodes=1:ppn=10
#PBS -k eo

module load idba/1.1.1 ;

b=$SAMPLE ;
enve=/nv/pmicro1/shared/apps/enveomics/Scripts
THR=10 ;

#---------------------------------------------------------

echo "==[ 05.assembly: $(date) ]" ;
cd $FOLDER/05.assembly ;

case "$TYPE" in
*g)
   time idba_ud --pre_correction -r $FA -o $SAMPLE --num_threads $THR ;;
t)
   time idba_tran --pre_correction -r $FA -o $SAMPLE --num_threads $THR ;;
*)
   echo "Unsupported data type: $TYPE" >&2 ;
   exit 1 ;
   ;;
esac ;

rm $SAMPLE/kmer
rm $SAMPLE/graph-*.fa
rm $SAMPLE/align-*
rm $SAMPLE/local-contig-*.fa
rm $SAMPLE/contig-*.fa

ln -s $SAMPLE/scaffold.fa $SAMPLE.AllContigs.fna ;
time $enve/FastA.length.pl $SAMPLE/scaffold.fa | awk '$2>=500{print $1}' > $SAMPLE.LargeContigs.ids ;
time $enve/FastA.filter.pl $SAMPLE.LargeContigs.ids $SAMPLE/scaffold.fa > $SAMPLE.LargeContigs.fna ;
rm $SAMPLE.LargeContigs.ids ;

#---------------------------------------------------------

echo "Done: $(date)." ;

