#!/bin/bash
#PBS -l nodes=1:ppn=10
#PBS -k eo

module load idba/1.1.1

b=$SAMPLE
shared=/nv/gpfs-gateway-pace1/project/bio-konstantinidis/shared3
enve=$shared/apps/enveomics/Scripts
THR=10

#---------------------------------------------------------

echo "==[ 05.assembly: $(date) ]"
cd $FOLDER/05.assembly

CMD=""
case "$TYPE" in
*g)
   CMD="idba_ud" ;;
t)
   CMD="idba_tran" ;;
*)
   echo "Unsupported data type: $TYPE" >&2
   exit 1
   ;;
esac
CMD="$CMD --pre_correction -r $FA -o $SAMPLE --num_threads $THR"
[[ -n "$FA_RL2" ]] && CMD="$CMD --read_level_2 $FA_RL2"
[[ -n "$FA_RL3" ]] && CMD="$CMD --read_level_3 $FA_RL3"
[[ -n "$FA_RL4" ]] && CMD="$CMD --read_level_4 $FA_RL4"
[[ -n "$FA_RL5" ]] && CMD="$CMD --read_level_5 $FA_RL5"

time $CMD

rm $SAMPLE/kmer
rm $SAMPLE/graph-*.fa
rm $SAMPLE/align-*
rm $SAMPLE/local-contig-*.fa
rm $SAMPLE/contig-*.fa

if [[ -s $SAMPLE/scaffold.fa ]] ; then
   ln -s $SAMPLE/scaffold.fa $SAMPLE.AllContigs.fna
else
   ln -s $SAMPLE/contig.fa $SAMPLE.AllContigs.fna
fi
time $enve/FastA.length.pl $SAMPLE.AllContigs.fna | awk '$2>=500{print $1}' \
   > $SAMPLE.LargeContigs.ids
time $enve/FastA.filter.pl $SAMPLE.LargeContigs.ids $SAMPLE.AllContigs.fna \
   > $SAMPLE.LargeContigs.fna
rm $SAMPLE.LargeContigs.ids

#---------------------------------------------------------

echo "Done: $(date)."

